#!/usr/bin/env bash

set -Eeuo pipefail

# ──────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────

REPO="thetimick/TiVPSUtils"
BRANCH="main"

INSTALL_DIR="/opt/TiVPSUtils"
SCRIPTS_DIR="${INSTALL_DIR}/src"

PROFILE_FILE="/etc/profile.d/tivpsutils.sh"

ARCHIVE_URL="https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"

# BEGIN GENERATED UI
# Generated by scripts/sync-ui.sh. Do not edit this block.
#!/usr/bin/env bash
# Shared console UI. Source this file; do not execute it.

if [[ -t 1 && -z "${NO_COLOR:-}" && "${TERM:-}" != dumb ]]; then
    RED=$'\033[31m' GREEN=$'\033[32m' YELLOW=$'\033[33m'
    BLUE=$'\033[34m' ACCENT=$'\033[35m' BOLD=$'\033[1m' DIM=$'\033[2m' RESET=$'\033[0m'
    # Lavender palette, with fallbacks for terminals with fewer colors.
    case "${COLORTERM:-}:${TERM:-}" in
        truecolor:*|24bit:*|*:*-direct|*:*truecolor*)
            ACCENT=$'\033[38;2;196;161;241m'
            GREEN=$'\033[38;2;145;215;175m'
            YELLOW=$'\033[38;2;239;199;131m'
            RED=$'\033[38;2;241;148;172m'
            BLUE=$'\033[38;2;145;189;244m'
            ;;
        *:*256color*)
            ACCENT=$'\033[38;5;183m' GREEN=$'\033[38;5;115m'
            YELLOW=$'\033[38;5;222m' RED=$'\033[38;5;211m' BLUE=$'\033[38;5;111m'
            ;;
    esac
else
    RED='' GREEN='' YELLOW='' BLUE='' ACCENT='' BOLD='' DIM='' RESET=''
fi

# Lavender: navigation; green: success; yellow: caution; rose: failure/destruction.
# Muted text: secondary information, exit and cancel. Labels work without color.
info() { printf '%b[INFO]%b %s\n' "$BLUE" "$RESET" "$*"; }
success() { printf '%b[ OK ]%b %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%b[WARN]%b %s\n' "$YELLOW" "$RESET" "$*"; }
error() { printf '%b[FAIL]%b %s\n' "$RED" "$RESET" "$*" >&2; }
die() { error "$@"; exit 1; }

ui_read() {
    printf '%b%s%b ' "$BOLD" "$1" "$RESET" >&2
    read -r "${2:-REPLY}"
}

pause() {
    printf '\n'
    local reply
    ui_read 'Нажми Enter, чтобы продолжить...' reply || true
}

confirm() {
    local answer
    ui_read "${1:-Продолжить?} [y/N]:" answer || return 1
    case "$answer" in
        y|Y|yes|YES|д|Д|да|Да|ДА) return 0 ;;
        *) return 1 ;;
    esac
}

clear_screen() {
    if [[ -t 1 && -n "${TERM:-}" && "$TERM" != dumb ]] && command -v clear >/dev/null 2>&1; then
        clear || true
    fi
}

require_root() {
    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        if command -v sudo >/dev/null 2>&1; then
            exec sudo -- "$0" "$@"
        fi
        die 'Скрипт необходимо запустить от root.'
    fi
}

ui_header() {
    printf '\n%bTiVPSUtils%b\n' "$DIM" "$RESET"
    printf '%b%s%b\n' "${ACCENT}${BOLD}" "$1" "$RESET"
    separator
    printf '\n'
}

separator() {
    printf '%b──────────────────────────────────────────────%b\n' "$DIM" "$RESET"
}

ui_field() {
    printf '  %b%s%b %s\n' "$DIM" "$1" "$RESET" "$2"
}

ui_command() {
    if [[ -n "${2:-}" ]]; then
        printf '  %b%-20s%b %s\n' "${ACCENT}${BOLD}" "$1" "$RESET" "$2"
    else
        printf '  %b%s%b\n' "${ACCENT}${BOLD}" "$1" "$RESET"
    fi
}

menu_item() {
    printf ' %b%2s)%b %b%s%b\n' "${3:-$ACCENT}${BOLD}" "$1" "$RESET" "$BOLD" "$2" "$RESET"
}

section_title() {
    printf '%b%s%b\n' "$BOLD" "$1" "$RESET"
}

read_menu_choice() {
    ui_read 'Выбери действие:' choice
}

bool_text() {
    if [[ "$1" == true ]]; then
        printf '%bВКЛ%b\n' "$GREEN" "$RESET"
    else
        printf '%bВЫКЛ%b\n' "$DIM" "$RESET"
    fi
}

yes_no() {
    if [[ "$1" == true ]]; then printf 'Да\n'; else printf 'Нет\n'; fi
}
# END GENERATED UI

# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

require_root() {
    if [[ $EUID -ne 0 ]]; then
        error "Операция требует root."
        printf "\n"
        printf "Запусти команду через sudo или от пользователя root.\n"
        exit 1
    fi
}

require_tar() {
    if ! command -v tar >/dev/null 2>&1; then
        error "tar не установлен."
        exit 1
    fi
}

download_file() {
    local url="$1"
    local output="$2"

    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$url" -o "$output"
        return
    fi

    if command -v wget >/dev/null 2>&1; then
        wget -qO "$output" "$url"
        return
    fi

    error "Требуется curl или wget."
    exit 1
}

get_metadata() {
    local script="$1"
    local key="$2"

    sed -n \
        "s/^#[[:space:]]*${key}[[:space:]]*=[[:space:]]*//p" \
        "$script" \
        | head -n 1
}

get_command_name() {
    local script="$1"
    local filename
    local name

    filename="$(basename "$script")"
    name="$(get_metadata "$script" "TI_ALIAS")"

    if [[ -z "$name" ]]; then
        name="${filename%.sh}"

        # Backward compatibility:
        # updater.sh -> tiupdate
        if [[ "$name" == "updater" ]]; then
            name="update"
        fi
    fi

    if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        return 1
    fi

    printf "%s" "$name"
}

get_description() {
    local script="$1"
    local description

    description="$(get_metadata "$script" "TI_DESCRIPTION")"

    if [[ -z "$description" ]]; then
        description="$(basename "$script")"
    fi

    printf "%s" "$description"
}

is_installed() {
    [[ -f "${INSTALL_DIR}/install.sh" ]]
}

is_running_installed_manager() {
    local source_path="${BASH_SOURCE[0]:-}"

    [[ -n "$source_path" ]] || return 1

    local resolved_source
    resolved_source="$(readlink -f "$source_path" 2>/dev/null || true)"

    [[ "$resolved_source" == "${INSTALL_DIR}/install.sh" ]]
}

# ──────────────────────────────────────────────
# Aliases
# ──────────────────────────────────────────────

generate_aliases() {
    require_root

    if ! is_installed; then
        error "TiVPSUtils не установлен."
        return 1
    fi

    info "Обновление aliases..."

    local temp_file
    temp_file="$(mktemp)"

    cat > "$temp_file" <<EOF
# TiVPSUtils
# Generated automatically by TiVPSUtils Manager.
# Do not edit manually.

alias tiinstall='${INSTALL_DIR}/install.sh'
EOF

    declare -A used_aliases
    used_aliases["tiinstall"]=1

    if [[ -d "$SCRIPTS_DIR" ]]; then
        while IFS= read -r -d '' script; do
            local command_name
            local alias_name

            if ! command_name="$(get_command_name "$script")"; then
                warn "Пропущен $(basename "$script"): некорректный TI_ALIAS."
                continue
            fi

            alias_name="ti${command_name}"

            if [[ -n "${used_aliases[$alias_name]:-}" ]]; then
                warn "Пропущен ${alias_name}: alias уже существует."
                continue
            fi

            used_aliases["$alias_name"]=1

            printf "alias %s='%s'\n" \
                "$alias_name" \
                "$script" \
                >> "$temp_file"

        done < <(
            find "$SCRIPTS_DIR" \
                -maxdepth 1 \
                -type f \
                -name "*.sh" \
                -print0 \
                | sort -z
        )
    fi

    install -m 0644 "$temp_file" "$PROFILE_FILE"
    rm -f "$temp_file"

    success "Aliases обновлены."
}

show_aliases() {
    printf "\n"
    section_title "Aliases TiVPSUtils"
    separator
    printf "\n"

    if [[ ! -f "$PROFILE_FILE" ]]; then
        warn "Aliases TiVPSUtils не установлены."
        printf "\n"
        return
    fi

    local found=false

    while IFS= read -r line; do
        if [[ "$line" =~ ^alias[[:space:]]+([^=]+)=\'(.*)\'$ ]]; then
            local alias_name="${BASH_REMATCH[1]}"
            local alias_path="${BASH_REMATCH[2]}"

            ui_command "$alias_name" "$alias_path"

            found=true
        fi
    done < "$PROFILE_FILE"

    if [[ "$found" == false ]]; then
        warn "Aliases не найдены."
    fi

    printf "\n"
}

clear_aliases() {
    require_root

    if [[ ! -f "$PROFILE_FILE" ]]; then
        warn "Aliases уже отсутствуют."
        return
    fi

    rm -f "$PROFILE_FILE"

    success "Aliases TiVPSUtils удалены."

    printf "\n"
    warn "Aliases, уже загруженные в текущую shell-сессию,"
    printf "останутся активными до повторного входа или перезапуска shell.\n"

    printf "\n"
    printf "Менеджер всё ещё можно запустить напрямую:\n"
    ui_command "${INSTALL_DIR}/install.sh"
}

# ──────────────────────────────────────────────
# Commands
# ──────────────────────────────────────────────

list_commands() {
    printf "\n"
    section_title "Доступные команды TiVPSUtils"
    separator
    printf "\n"

    ui_command "tiinstall" "Менеджер TiVPSUtils"

    if [[ ! -d "$SCRIPTS_DIR" ]]; then
        printf "\n"
        warn "Скрипты не установлены."
        printf "\n"
        return
    fi

    while IFS= read -r -d '' script; do
        local command_name
        local description

        if ! command_name="$(get_command_name "$script")"; then
            continue
        fi

        description="$(get_description "$script")"

        ui_command "ti${command_name}" "$description"

    done < <(
        find "$SCRIPTS_DIR" \
            -maxdepth 1 \
            -type f \
            -name "*.sh" \
            -print0 \
            | sort -z
    )

    printf "\n"
}

# ──────────────────────────────────────────────
# Install / Update
# ──────────────────────────────────────────────

install_latest() (
    require_root
    require_tar

    local temp_dir
    local archive_path
    local extracted_dir
    local staging_dir=""
    local old_dir=""

    temp_dir="$(mktemp -d)"
    archive_path="${temp_dir}/repo.tar.gz"
    extracted_dir="${temp_dir}/repo"

    cleanup_install() {
        if [[ -n "${staging_dir:-}" && -d "${staging_dir:-}" ]]; then
            rm -rf "$staging_dir"
        fi

        if [[ -n "${temp_dir:-}" && -d "${temp_dir:-}" ]]; then
            rm -rf "$temp_dir"
        fi
    }

    trap cleanup_install EXIT

    printf "\n"

    info "Загрузка TiVPSUtils..."
    download_file "$ARCHIVE_URL" "$archive_path"

    info "Распаковка архива..."

    mkdir -p "$extracted_dir"

    tar \
        -xzf "$archive_path" \
        -C "$extracted_dir" \
        --strip-components=1

    if [[ ! -f "${extracted_dir}/install.sh" ]]; then
        error "install.sh отсутствует в репозитории."
        exit 1
    fi

    if [[ ! -d "${extracted_dir}/src" ]]; then
        warn "Директория src отсутствует в репозитории."
    fi

    info "Подготовка файлов..."

    staging_dir="$(mktemp -d "${INSTALL_DIR}.new.XXXXXX")"

    cp -a "${extracted_dir}/." "$staging_dir/"

    find "$staging_dir" \
        -type f \
        -name "*.sh" \
        -exec chmod 0755 {} \;

    info "Установка в ${INSTALL_DIR}..."

    if [[ -d "$INSTALL_DIR" ]]; then
        old_dir="${INSTALL_DIR}.old.$$"

        rm -rf "$old_dir"
        mv "$INSTALL_DIR" "$old_dir"
    fi

    if ! mv "$staging_dir" "$INSTALL_DIR"; then
        error "Не удалось установить TiVPSUtils."

        if [[ -n "$old_dir" && -d "$old_dir" ]]; then
            warn "Восстановление предыдущей версии..."
            mv "$old_dir" "$INSTALL_DIR"
        fi

        exit 1
    fi

    staging_dir=""

    if [[ -n "$old_dir" && -d "$old_dir" ]]; then
        rm -rf "$old_dir"
    fi

    generate_aliases

    printf "\n"
    success "TiVPSUtils успешно установлен."

    printf "\n"
    printf "Путь: %b%s%b\n" \
        "$ACCENT" \
        "$INSTALL_DIR" \
        "$RESET"

    list_commands

    printf "Для применения aliases в текущей shell-сессии:\n"
    printf "\n"
    ui_command "source ${PROFILE_FILE}"

    printf "\n"
)

# ──────────────────────────────────────────────
# Uninstall
# ──────────────────────────────────────────────

uninstall_all() {
    require_root

    local force="${1:-false}"

    if [[ "$force" != "true" ]]; then
        printf "\n"

        if ! confirm "Полностью удалить TiVPSUtils?"; then
            warn "Удаление отменено."
            return
        fi
    fi

    printf "\n"
    info "Удаление aliases..."

    rm -f "$PROFILE_FILE"

    info "Удаление ${INSTALL_DIR}..."

    # Если менеджер запущен из INSTALL_DIR, Bash уже держит
    # открытый скрипт, поэтому удалить каталог безопасно.
    rm -rf "$INSTALL_DIR"

    printf "\n"
    success "TiVPSUtils полностью удалён."

    printf "\n"
    warn "Aliases текущей shell-сессии могут оставаться активными"
    printf "до повторного входа или перезапуска shell.\n"

    printf "\n"
}

# ──────────────────────────────────────────────
# Header
# ──────────────────────────────────────────────

show_header() {
    ui_header "Менеджер установки"
}

# ──────────────────────────────────────────────
# Menu
# ──────────────────────────────────────────────

show_menu() {
    while true; do
        clear_screen
        show_header
        section_title "Управление:"
        printf '\n'
        menu_item "1" "Установить / обновить TiVPSUtils"
        printf '\n'
        menu_item "2" "Показать доступные команды"
        menu_item "3" "Показать aliases"
        menu_item "4" "Пересоздать aliases"
        printf '\n'
        menu_item "5" "Очистить aliases" "$YELLOW"
        menu_item "6" "Полностью удалить TiVPSUtils" "$RED"
        printf '\n'
        menu_item "0" "Выход" "$DIM"
        printf '\n'

        local choice
        read_menu_choice || return 0

        case "$choice" in
            1)
                install_latest
                ;;
            2)
                list_commands
                ;;
            3)
                show_aliases
                ;;
            4)
                printf "\n"
                generate_aliases
                printf "\n"
                ;;
            5)
                printf "\n"

                if confirm "Удалить все aliases TiVPSUtils?"; then
                    printf "\n"
                    clear_aliases
                else
                    warn "Операция отменена."
                fi
                ;;
            6)
                uninstall_all
                return
                ;;
            0)
                printf "\n"
                return
                ;;
            *)
                printf "\n"
                error "Неизвестный пункт: ${choice}"
                ;;
        esac
        pause
    done
}

# ──────────────────────────────────────────────
# Help
# ──────────────────────────────────────────────

show_help() {
    show_header

    section_title "Использование"
    separator
    printf "\n"

    ui_command "tiinstall"
    printf "      Открыть интерактивный менеджер.\n"

    printf "\n"

    ui_command "tiinstall update"
    printf "      Скачать и установить последнюю версию.\n"

    printf "\n"

    ui_command "tiinstall list"
    printf "      Показать доступные команды.\n"

    printf "\n"

    ui_command "tiinstall aliases"
    printf "      Показать установленные aliases.\n"

    printf "\n"

    ui_command "tiinstall rebuild-aliases"
    printf "      Пересоздать aliases.\n"

    printf "\n"

    ui_command "tiinstall clear-aliases"
    printf "      Удалить aliases TiVPSUtils.\n"

    printf "\n"

    ui_command "tiinstall uninstall"
    printf "      Полностью удалить TiVPSUtils.\n"

    printf "\n"

    ui_command "tiinstall uninstall --yes"
    printf "      Удалить TiVPSUtils без подтверждения.\n"

    printf "\n"

    ui_command "tiinstall help"
    printf "      Показать справку.\n"

    printf "\n"
}

# ──────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────

main() {
    local command="${1:-}"

    # При запуске через:
    #
    # curl .../install.sh | sudo bash
    #
    # автоматически запускаем установку.
    #
    # При запуске установленного:
    #
    # tiinstall
    #
    # открываем менеджер.

    if [[ -z "$command" ]]; then
        if ! is_running_installed_manager; then
            install_latest
            return
        fi

        show_menu
        return
    fi

    case "$command" in
        install|update|upgrade)
            install_latest
            ;;

        list|commands)
            list_commands
            ;;

        aliases)
            show_aliases
            ;;

        rebuild-aliases)
            printf "\n"
            generate_aliases
            printf "\n"
            ;;

        clear-aliases)
            printf "\n"
            clear_aliases
            printf "\n"
            ;;

        uninstall|remove)
            if [[ "${2:-}" == "--yes" ]]; then
                uninstall_all true
            else
                uninstall_all false
            fi
            ;;

        help|-h|--help)
            show_help
            ;;

        *)
            error "Неизвестная команда: ${command}"
            printf "\n"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
