#!/usr/bin/env bash
# Keep curl | bash self-contained; edit src/helpers/ui.sh, then run this script.
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
output="$(mktemp)"
trap 'rm -f -- "$output"' EXIT

awk -v ui="$ROOT/src/helpers/ui.sh" '
    /^# BEGIN GENERATED UI$/ {
        print
        print "# Generated by scripts/sync-ui.sh. Do not edit this block."
        while ((getline line < ui) > 0) print line
        close(ui)
        skip = 1
        next
    }
    /^# END GENERATED UI$/ { skip = 0 }
    !skip { print }
' "$ROOT/install.sh" > "$output"

if [[ "${1:-}" == --check ]]; then
    if ! cmp -s "$output" "$ROOT/install.sh"; then
        printf 'Installer UI is out of date. Run: bash scripts/sync-ui.sh\n' >&2
        exit 1
    fi
else
    cat "$output" > "$ROOT/install.sh"
fi
